from __future__ import annotations

from src.core.schema import DifyNodeType


NODE_SELECTION_PRIORITY: list[DifyNodeType] = [
    DifyNodeType.if_else,
    DifyNodeType.iteration,
    DifyNodeType.variable_aggregator,
    DifyNodeType.http_request,
    DifyNodeType.template_transform,
    DifyNodeType.tool,
    DifyNodeType.doc_extractor,
    DifyNodeType.parameter_extractor,
    DifyNodeType.llm,
    DifyNodeType.code,
]


def _normalize_keyword(keyword: str) -> str:
    return keyword.strip().lower()


def _dedupe_rules(rules: list[dict[str, str]]) -> list[dict[str, str]]:
    seen: set[tuple[str, str]] = set()
    unique_rules: list[dict[str, str]] = []
    for rule in rules:
        normalized_keyword = _normalize_keyword(rule["keyword"])
        if not normalized_keyword:
            continue
        key = (normalized_keyword, rule["node_type"])
        if key in seen:
            continue
        seen.add(key)
        unique_rules.append({"keyword": normalized_keyword, "node_type": rule["node_type"]})
    return unique_rules


def _expand_rules(
    node_type: DifyNodeType,
    verbs_en: list[str],
    objects_en: list[str],
    verbs_zh: list[str],
    objects_zh: list[str],
) -> list[dict[str, str]]:
    rules: list[dict[str, str]] = []
    for verb in verbs_en:
        for obj in objects_en:
            rules.append({"keyword": f"{verb}_{obj}", "node_type": node_type.value})
            rules.append({"keyword": f"{verb} {obj}", "node_type": node_type.value})
    for verb in verbs_zh:
        for obj in objects_zh:
            rules.append({"keyword": f"{verb}{obj}", "node_type": node_type.value})
    return rules


def _build_mapping_rules() -> list[dict[str, str]]:
    rules: list[dict[str, str]] = [
        {"keyword": "start_node", "node_type": DifyNodeType.start.value},
        {"keyword": "start", "node_type": DifyNodeType.start.value},
        {"keyword": "end_node", "node_type": DifyNodeType.end.value},
        {"keyword": "end", "node_type": DifyNodeType.end.value},
        {"keyword": "if", "node_type": DifyNodeType.if_else.value},
        {"keyword": "when", "node_type": DifyNodeType.if_else.value},
        {"keyword": "condition", "node_type": DifyNodeType.if_else.value},
        {"keyword": "条件", "node_type": DifyNodeType.if_else.value},
        {"keyword": "判断", "node_type": DifyNodeType.if_else.value},
        {"keyword": "iterate", "node_type": DifyNodeType.iteration.value},
        {"keyword": "for_each", "node_type": DifyNodeType.iteration.value},
        {"keyword": "loop", "node_type": DifyNodeType.iteration.value},
        {"keyword": "遍历", "node_type": DifyNodeType.iteration.value},
        {"keyword": "批量", "node_type": DifyNodeType.iteration.value},
        {"keyword": "aggregate", "node_type": DifyNodeType.variable_aggregator.value},
        {"keyword": "merge_results", "node_type": DifyNodeType.variable_aggregator.value},
        {"keyword": "汇总", "node_type": DifyNodeType.variable_aggregator.value},
        {"keyword": "聚合", "node_type": DifyNodeType.variable_aggregator.value},
    ]

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.llm,
            verbs_en=[
                "generate",
                "summarize",
                "rewrite",
                "analyze",
                "translate",
                "expand",
                "shorten",
                "polish",
                "draft",
                "paraphrase",
                "explain",
                "outline",
                "brainstorm",
                "answer",
                "respond",
                "refine",
                "review",
                "improve",
                "elaborate",
                "compose",
            ],
            objects_en=[
                "article",
                "document",
                "email",
                "report",
                "tutorial",
                "content",
                "question",
                "response",
                "description",
                "summary",
                "proposal",
                "review",
                "script",
                "story",
                "announcement",
                "meeting_minutes",
                "plan",
                "outline",
                "faq",
                "caption",
            ],
            verbs_zh=[
                "生成",
                "总结",
                "改写",
                "分析",
                "翻译",
                "扩写",
                "缩写",
                "润色",
                "撰写",
                "解释",
                "整理",
                "回答",
                "回复",
                "优化",
                "提炼",
                "审阅",
                "完善",
                "编写",
            ],
            objects_zh=[
                "文章",
                "文档",
                "邮件",
                "报告",
                "教程",
                "内容",
                "问题",
                "回复",
                "说明",
                "摘要",
                "方案",
                "脚本",
                "故事",
                "公告",
                "会议纪要",
                "计划",
                "大纲",
                "问答",
                "标题",
                "文案",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.code,
            verbs_en=[
                "transform",
                "clean",
                "normalize",
                "parse",
                "validate",
                "convert",
                "compute",
                "merge",
                "filter",
                "sort",
                "deduplicate",
                "reshape",
                "map",
                "reduce",
                "join",
                "split",
                "flatten",
                "standardize",
                "sanitize",
                "enrich",
            ],
            objects_en=[
                "json",
                "csv",
                "records",
                "dataset",
                "payload",
                "schema",
                "fields",
                "results",
                "items",
                "numbers",
                "dates",
                "table",
                "logs",
                "metrics",
                "values",
                "rows",
                "columns",
                "objects",
                "arrays",
                "events",
            ],
            verbs_zh=[
                "清洗",
                "转换",
                "规范化",
                "解析",
                "校验",
                "计算",
                "合并",
                "过滤",
                "排序",
                "去重",
                "映射",
                "拆分",
                "聚合",
                "拼接",
                "展平",
                "标准化",
                "补全",
                "修复",
            ],
            objects_zh=[
                "数据",
                "记录",
                "结果",
                "字段",
                "表格",
                "列表",
                "时间",
                "数字",
                "结构",
                "内容",
                "日志",
                "指标",
                "事件",
                "对象",
                "数组",
                "行数据",
                "列数据",
                "值",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.http_request,
            verbs_en=[
                "request",
                "fetch",
                "call",
                "post",
                "get",
                "put",
                "delete",
                "invoke",
                "send",
                "query",
                "submit",
                "trigger",
                "sync",
                "pull",
                "push",
            ],
            objects_en=[
                "api",
                "endpoint",
                "service",
                "weather_api",
                "crm_api",
                "payment_api",
                "search_api",
                "user_api",
                "order_api",
                "external_service",
                "external_api",
                "notification_api",
                "inventory_api",
                "analytics_api",
                "billing_api",
                "shipping_api",
                "ticket_api",
                "risk_api",
                "profile_api",
                "catalog_api",
                "gateway_api",
            ],
            verbs_zh=[
                "请求",
                "调用",
                "获取",
                "提交",
                "发送",
                "查询",
                "拉取",
                "访问",
                "触发",
                "连接",
                "同步",
                "推送",
            ],
            objects_zh=[
                "接口",
                "服务",
                "天气接口",
                "订单接口",
                "支付接口",
                "用户接口",
                "外部服务",
                "外部接口",
                "系统接口",
                "查询接口",
                "数据接口",
                "通知接口",
                "库存接口",
                "风控接口",
                "账单接口",
                "物流接口",
                "工单接口",
                "目录接口",
                "网关接口",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.template_transform,
            verbs_en=[
                "format",
                "compose",
                "fill",
                "render",
                "template",
                "assemble",
                "build",
                "structure",
                "layout",
                "organize",
                "arrange",
                "construct",
            ],
            objects_en=[
                "template",
                "message",
                "prompt",
                "report",
                "email",
                "notice",
                "summary",
                "output",
                "document",
                "response",
                "bullet_points",
                "table_text",
                "digest",
                "memo",
                "announcement",
                "meeting_note",
            ],
            verbs_zh=[
                "模板化",
                "格式化",
                "拼接",
                "填充",
                "渲染",
                "组装",
                "构建",
                "整理",
                "排版",
                "编排",
                "组织",
            ],
            objects_zh=[
                "模板",
                "消息",
                "提示词",
                "报告",
                "邮件",
                "通知",
                "摘要",
                "输出",
                "文档",
                "回复",
                "纪要",
                "公告",
                "清单",
                "段落",
                "文本",
                "内容",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.tool,
            verbs_en=[
                "use",
                "call",
                "invoke",
                "run",
                "search",
                "query",
                "execute",
                "trigger",
                "lookup",
                "scan",
            ],
            objects_en=[
                "tool",
                "plugin",
                "web_tool",
                "search_tool",
                "crawler_tool",
                "calendar_tool",
                "mail_tool",
                "knowledge_tool",
                "analysis_tool",
                "automation_tool",
                "ocr_tool",
                "database_tool",
                "filesystem_tool",
                "sheet_tool",
                "monitor_tool",
            ],
            verbs_zh=[
                "调用",
                "使用",
                "执行",
                "运行",
                "检索",
                "查询",
                "触发",
                "查找",
                "扫描",
            ],
            objects_zh=[
                "工具",
                "插件",
                "搜索工具",
                "网页工具",
                "邮件工具",
                "日历工具",
                "自动化工具",
                "分析工具",
                "知识工具",
                "脚本工具",
                "OCR工具",
                "数据库工具",
                "表格工具",
                "监控工具",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.doc_extractor,
            verbs_en=[
                "extract",
                "read",
                "parse",
                "load",
                "ingest",
                "decode",
                "recognize",
                "scan",
                "pull_text_from",
                "import",
            ],
            objects_en=[
                "document",
                "pdf",
                "docx",
                "file_text",
                "attachment",
                "contract",
                "invoice",
                "manual",
                "specification",
                "paper",
                "resume",
                "statement",
                "policy",
                "guideline",
                "ebook",
            ],
            verbs_zh=[
                "提取",
                "读取",
                "解析",
                "载入",
                "导入",
                "识别",
                "扫描",
                "抽取",
                "获取",
            ],
            objects_zh=[
                "文档",
                "PDF",
                "合同",
                "发票",
                "说明书",
                "附件",
                "报告",
                "论文",
                "规格书",
                "手册",
                "简历",
                "声明",
                "政策",
                "指引",
                "电子书",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.parameter_extractor,
            verbs_en=[
                "extract",
                "identify",
                "classify",
                "detect",
                "tag",
                "route",
                "recognize",
                "locate",
                "find",
                "parse",
                "map",
                "label",
            ],
            objects_en=[
                "parameters",
                "entities",
                "intents",
                "labels",
                "slots",
                "categories",
                "keywords",
                "fields",
                "types",
                "attributes",
                "language",
                "priority",
                "risk_tags",
                "topic",
                "region",
                "product_name",
            ],
            verbs_zh=[
                "抽取",
                "识别",
                "分类",
                "检测",
                "标注",
                "路由",
                "定位",
                "提取",
                "映射",
                "解析",
            ],
            objects_zh=[
                "参数",
                "实体",
                "意图",
                "标签",
                "槽位",
                "类别",
                "关键词",
                "字段",
                "类型",
                "属性",
                "语言",
                "优先级",
                "风险标签",
                "主题",
                "地区",
                "产品名",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.variable_aggregator,
            verbs_en=[
                "merge",
                "aggregate",
                "collect",
                "combine",
                "consolidate",
                "join",
                "fuse",
                "stack",
                "union",
                "summarize",
            ],
            objects_en=[
                "results",
                "outputs",
                "responses",
                "branch_data",
                "records",
                "items",
                "summaries",
                "scores",
                "metrics",
                "fragments",
                "logs",
                "labels",
                "signals",
                "statistics",
                "insights",
            ],
            verbs_zh=[
                "汇总",
                "聚合",
                "合并",
                "整合",
                "收集",
                "拼接",
                "融合",
                "归并",
                "汇编",
                "汇聚",
            ],
            objects_zh=[
                "结果",
                "输出",
                "响应",
                "分支数据",
                "记录",
                "条目",
                "摘要",
                "评分",
                "指标",
                "片段",
                "日志",
                "标签",
                "信号",
                "统计",
                "结论",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.iteration,
            verbs_en=[
                "iterate",
                "loop",
                "for_each",
                "batch_process",
                "traverse",
                "process_each",
                "scan_each",
                "handle_each",
                "walk_through",
                "run_for_each",
            ],
            objects_en=[
                "items",
                "records",
                "files",
                "documents",
                "rows",
                "tasks",
                "urls",
                "messages",
                "images",
                "products",
                "users",
                "orders",
                "tickets",
                "chunks",
                "pages",
                "entries",
                "batches",
                "events",
            ],
            verbs_zh=[
                "遍历",
                "循环",
                "逐条处理",
                "批量处理",
                "依次处理",
                "按条处理",
                "逐个处理",
                "逐项处理",
                "轮询",
                "逐页处理",
            ],
            objects_zh=[
                "列表",
                "记录",
                "文件",
                "文档",
                "行数据",
                "任务",
                "链接",
                "消息",
                "图片",
                "商品",
                "用户",
                "订单",
                "工单",
                "文本块",
                "页面",
                "条目",
                "批次",
                "事件",
            ],
        )
    )

    rules.extend(
        _expand_rules(
            node_type=DifyNodeType.if_else,
            verbs_en=[
                "check",
                "judge",
                "decide",
                "route_by",
                "branch_by",
                "verify",
                "inspect",
                "validate",
                "compare",
                "evaluate",
            ],
            objects_en=[
                "condition",
                "status",
                "empty_input",
                "file_exists",
                "threshold",
                "validity",
                "risk_level",
                "language",
                "intent",
                "priority",
                "permission",
                "quota",
                "quality",
                "score",
                "availability",
                "compliance",
            ],
            verbs_zh=[
                "判断",
                "检查",
                "分流",
                "路由",
                "校验",
                "核对",
                "比较",
                "评估",
                "鉴别",
                "判定",
            ],
            objects_zh=[
                "条件",
                "状态",
                "输入为空",
                "文件存在",
                "阈值",
                "有效性",
                "风险等级",
                "语言",
                "意图",
                "优先级",
                "权限",
                "配额",
                "质量",
                "分数",
                "可用性",
                "合规性",
            ],
        )
    )

    return _dedupe_rules(rules)


MAPPING_RULES: list[dict[str, str]] = _build_mapping_rules()
MAPPING_RULES_BY_NODE_TYPE: dict[str, list[str]] = {}
for _rule in MAPPING_RULES:
    MAPPING_RULES_BY_NODE_TYPE.setdefault(_rule["node_type"], []).append(_rule["keyword"])

if len(MAPPING_RULES) < 500:
    raise ValueError(f"节点映射规则数量不足，当前仅 {len(MAPPING_RULES)} 条")
