from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.core.schema import UTR
from src.skeleton_planning.skeleton_planner import SkeletonPlanner


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Plan workflow skeletons from generated UTR records.")
    parser.add_argument(
        "--input-file",
        default="generated_data/utr_generation/utrs.jsonl",
        help="Input JSONL file generated by scripts/01_generate_utrs.py.",
    )
    parser.add_argument(
        "--output-dir",
        default="generated_data/skeleton_planning/iter2",
        help="Directory for skeletons.jsonl and errors.json.",
    )
    parser.add_argument(
        "--max-records",
        type=int,
        default=0,
        help="Optional maximum number of records to process. 0 means all records.",
    )
    return parser.parse_args()


def iter_jsonl(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            records.append(json.loads(line))
    return records


def main() -> None:
    args = parse_args()
    input_file = Path(args.input_file)
    output_dir = Path(args.output_dir)
    output_file = output_dir / "skeletons.jsonl"
    error_file = output_dir / "errors.json"

    if not input_file.exists():
        raise FileNotFoundError(f"Input file not found: {input_file}")

    output_dir.mkdir(parents=True, exist_ok=True)
    planner = SkeletonPlanner()
    records = iter_jsonl(input_file)
    if args.max_records > 0:
        records = records[: args.max_records]

    results: list[dict[str, Any]] = []
    errors: list[dict[str, str]] = []

    for record in records:
        record_id = str(record.get("id", ""))
        instruction = str(record.get("instruction", ""))
        try:
            utr = UTR.model_validate(record["utr"])
            skeleton = planner.plan(utr)
            results.append(
                {
                    "id": record_id,
                    "instruction": instruction,
                    "skeleton": skeleton.model_dump(),
                }
            )
            print(f"[OK] planned skeleton: {record_id}")
        except Exception as exc:
            errors.append({"id": record_id, "instruction": instruction, "error": str(exc)})
            print(f"[ERROR] failed skeleton planning: {record_id}: {exc}")

    with output_file.open("w", encoding="utf-8") as stream:
        for result in results:
            stream.write(json.dumps(result, ensure_ascii=False) + "\n")

    error_file.write_text(json.dumps(errors, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Completed. Success: {len(results)}, Errors: {len(errors)}")
    print(f"Results: {output_file}")
    print(f"Errors: {error_file}")


if __name__ == "__main__":
    main()
